version: '3.6'

services:
  adapter1_net1:
    build:
      context: ./
      dockerfile: ./adapter/adapterdgu/Dockerfile
    env_file:
    - ./env_connect_to_network_2.env
    ports:
     - "8081:8081"
  adapter1_net2:
    build:
      context: ./
      dockerfile: ./adapter/adapterdgu/Dockerfile
    env_file:
    - ./env_connect_to_network_1.env
    ports:
#     - "10.8.0.13:8082:8082"     
     - "8082:8082"     